---
- hosts: all  # noqa: name[play]
  become: true
  vars:
      is_container: false

  roles:

      - role: "{{ playbook_dir }}"
        system_is_container: "{{ is_container | default(false) }}"
        rhel8cis_skip_for_travis: false
