---

- name: "5.2.1.1 | PATCH | Ensure auditd is installed"
  when:
      - rhel8cis_rule_5_2_1_1
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - NIST800-53R5_AU-2
      - NIST800-53R5_AU-3
      - NIST800-53R5_AU-12
      - NIST800-53R5_SI-5
      - auditd
      - rule_5.2.1.1
  block:
      - name: "5.2.1.1 | PATCH | Ensure auditd is installed | Install auditd packages"
        ansible.builtin.package:
            name: audit
            state: present
        when: '"auditd" not in ansible_facts.packages'

      - name: "5.2.1.1 | PATCH | Ensure auditd is installed | Install auditd-lib packages"
        ansible.builtin.package:
            name: audit-libs
            state: present
        when: '"auditd-lib" not in ansible_facts.packages'

- name: "5.2.1.2 | PATCH | Ensure auditing for processes that start prior to auditd is enabled"
  when:
      - rhel8cis_rule_5_2_1_2
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - auditd
      - grub
      - rule_5.2.1.2
  notify: Rebuild_grub
  block:
      - name: "5.2.1.2 | AUDIT | Ensure auditing for processes that start prior to auditd is enabled | Get GRUB_CMDLINE_LINUX"
        ansible.builtin.shell: grep 'GRUB_CMDLINE_LINUX=' /etc/default/grub | sed 's/.$//'
        changed_when: false
        failed_when: false
        check_mode: false
        register: discovered_auditd_grub_cmdline_linux

      - name: "5.2.1.2 | PATCH | Ensure auditing for processes that start prior to auditd is enabled | Replace existing setting"
        when: "'audit=' in discovered_auditd_grub_cmdline_linux.stdout"
        ansible.builtin.replace:
            path: /etc/default/grub
            regexp: 'audit=.'
            replace: 'audit=1'

      - name: "5.2.1.2 | PATCH | Ensure auditing for processes that start prior to auditd is enabled | Add audit setting if missing"
        when: "'audit=' not in discovered_auditd_grub_cmdline_linux.stdout"
        ansible.builtin.lineinfile:
            path: /etc/default/grub
            regexp: '^GRUB_CMDLINE_LINUX='
            line: '{{ discovered_auditd_grub_cmdline_linux.stdout }} audit=1"'

- name: "5.2.1.3 | PATCH | Ensure audit_backlog_limit is sufficient"
  when:
      - rhel8cis_rule_5_2_1_3
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - auditd
      - NIST800-53R5_AU-2
      - NIST800-53R5_AU-12
      - NIST800-53R5_SI-5
      - grub
      - rule_5.2.1.3
  notify: Rebuild_grub
  block:
      - name: "5.2.1.3 | AUDIT | Ensure audit_backlog_limit is sufficient | Get GRUB_CMDLINE_LINUX"
        ansible.builtin.shell: grep 'GRUB_CMDLINE_LINUX=' /etc/default/grub | sed 's/.$//'
        changed_when: false
        failed_when: false
        check_mode: false
        register: discovered_backlog_grub_cmdline_linux

      - name: "5.2.1.3 | PATCH | Ensure audit_backlog_limit is sufficient | Replace existing setting"
        ansible.builtin.replace:
            path: /etc/default/grub
            regexp: 'audit_backlog_limit=\d+'
            replace: 'audit_backlog_limit={{ rhel8cis_audit_back_log_limit }}'
        when: "'audit_backlog_limit=' in discovered_backlog_grub_cmdline_linux.stdout"

      - name: "5.2.1.3 | PATCH | Ensure audit_backlog_limit is sufficient | Add audit_backlog_limit setting if missing"
        ansible.builtin.lineinfile:
            path: /etc/default/grub
            regexp: '^GRUB_CMDLINE_LINUX='
            line: '{{ discovered_backlog_grub_cmdline_linux.stdout }} audit_backlog_limit={{ rhel8cis_audit_back_log_limit }}"'
        when: "'audit_backlog_limit=' not in discovered_backlog_grub_cmdline_linux.stdout"

- name: "5.2.1.4 | PATCH | Ensure auditd service is enabled"
  when:
      - rhel8cis_rule_5_2_1_4
  tags:
      - level2-server
      - level2-workstation
      - automated
      - patch
      - NIST800-53R5_AU-2
      - NIST800-53R5_AU-12
      - NIST800-53R5_SI-5
      - auditd
      - rule_5.2.1.4
  ansible.builtin.service:
      name: auditd
      state: started
      enabled: true
