---

- name: "6.2.3.1 | PATCH | Ensure access to all logfiles has been configured"
  when:
    - rhel8cis_rule_6_2_3_1
    - rhel8cis_disruption_high
  tags:
    - level1-server
    - level1-workstation
    - patch
    - NIST800-53R5_AC-3
    - NIST800-53R5_MP-2
    - logfiles
    - rule_6.2.3.1
  block:
    - name: "6.2.3.1 | AUDIT | Ensure access to all logfiles has been configured | find log files"
      ansible.builtin.shell: |
        set -o pipefail
        find -L /var/log -type f \( -perm /0137 -o ! -user root -o ! -group root \) -exec ls -l {} \;
      args:
        executable: "{{ rhel8cis_shell_executable }}"
      changed_when: false
      failed_when: false
      check_mode: false
      register: discovered_logfiles

    - name: "6.2.3.1 | PATCH | Ensure access to all logfiles has been configured | change permissions SSSD min 660"
      when:
        - discovered_logfiles.stdout_lines | length > 0
        - item is match("/var/log/(gdm|sssd)")
      ansible.builtin.file:
        path: "{{ item }}"
        mode: 'ug-x,o-rwx'
      failed_when: discovered_logfile_sssd_list.state not in '[ file, absent ]'
      check_mode: false
      register: discovered_logfile_sssd_list
      loop: "{{ discovered_logfiles.stdout_lines }}"

    - name: "6.2.3.1 | PATCH | Ensure access to all logfiles has been configured | change permissions tmp min 664"
      when:
        - discovered_logfiles.stdout_lines | length > 0
        - item is match("/var/log/((u|b|w)tmp*|lastlog)")
      ansible.builtin.file:
        path: "{{ item }}"
        mode: 'ug-x,o-wx'
      failed_when: discovered_logfile_tmp_list.state not in '[ file, absent ]'
      check_mode: false
      register: discovered_logfile_tmp_list
      loop: "{{ discovered_logfiles.stdout_lines }}"

    - name: "6.2.3.1 | PATCH | Ensure access to all logfiles has been configured | change permissions else all 640"
      when:
        - discovered_logfiles.stdout_lines | length > 0
        - item is not match("/var/log/((u|b|w)tmp*|lastlog|sssd)")
      ansible.builtin.file:
        path: "{{ item }}"
        mode: 'u-x,g-wx,o-rwx'
      failed_when: discovered_logfile_not_tmp_list.state not in '[ file, absent ]'
      check_mode: false
      register: discovered_logfile_not_tmp_list
      loop: "{{ discovered_logfiles.stdout_lines }}"
