---

- name: "SCORED | 1.8.1.1 | PATCH | Ensure message of the day is configured properly"
  template:
      src: etc/motd.j2
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644

  when:
      - rhel8cis_rule_1_8_1_1
  tags:
      - level1-server
      - level1-workstation
      - banner
      - patch
      - rule_1.8.1.1

- name: "SCORED | 1.8.1.2 | PATCH | Ensure local login warning banner is configured properly"
  template:
      src: etc/issue.j2
      dest: /etc/issue
      owner: root
      group: root
      mode: 0644
  when:
      - rhel8cis_rule_1_8_1_2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_1.8.1.2

- name: "SCORED | 1.8.1.3 | PATCH | Ensure remote login warning banner is configured properly"
  template:
      src: etc/issue.net.j2
      dest: /etc/issue.net
      owner: root
      group: root
      mode: 0644
  when:
      - rhel8cis_rule_1_8_1_3
  tags:
      - level1-server
      - level1-workstation
      - banner
      - patch
      - rule_1.8.1.3

- name: "SCORED | 1.8.1.4 | PATCH | Ensure permissions on /etc/motd are configured"
  file:
      dest: /etc/motd
      state: file
      owner: root
      group: root
      mode: 0644
  when:
      - rhel8cis_rule_1_8_1_4
  tags:
      - level1-server
      - level1-workstation
      - perms
      - patch
      - rule_1.8.1.4

- name: "SCORED | 1.8.1.5 | PATCH | Ensure permissions on /etc/issue are configured"
  file:
      dest: /etc/issue
      state: file
      owner: root
      group: root
      mode: 0644
  when:
      - rhel8cis_rule_1_8_1_5
  tags:
      - level1-server
      - level1-workstation
      - perms
      - patch
      - rule_1.8.1.5

- name: "NOTSCORED | 1.8.1.6 | PATCH | Ensure permissions on /etc/issue.net are configured"
  file:
      dest: /etc/issue.net
      state: file
      owner: root
      group: root
      mode: 0644
  when:
      - rhel8cis_rule_1_8_1_6
  tags:
      - level1-server
      - level1-workstation
      - perms
      - patch
      - rule_1.8.1.6
