---

- name: "1.3.1.1 | PATCH | Ensure SELinux is installed"
  when: rhel8cis_rule_1_3_1_1
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - NIST800-53R5_AC-3
    - NIST800-53R5_MP-2
    - rule_1.3.1.1
  ansible.builtin.package:
    name: libselinux
    state: present

- name: "1.3.1.2 | PATCH | Ensure SELinux is not disabled in bootloader configuration"
  when: rhel8cis_rule_1_3_1_2
  tags:
    - level1-server
    - level1-workstation
    - patch
    - NIST800-53R5_AC-3
    - NIST800-53R5_MP-2
    - rule_1.3.1.2
  notify: Rebuild grub
  block:
    - name: "1.3.1.2 | AUDIT | Ensure SELinux is not disabled in bootloader configuration | current state"
      ansible.builtin.shell: |
        set -o pipefail
        grubby --info=ALL | grep -Po '(selinux|enforcing)=0\b'
      args:
        executable: "{{ rhel8cis_shell_executable }}"
      failed_when: discovered_selinux_bootloader_cfg.rc not in [ 0, 1 ]
      changed_when: false
      register: discovered_selinux_bootloader_cfg

    - name: "1.3.1.2 | PATCH | Ensure SELinux is not disabled in bootloader configuration | Set state"
      when: discovered_selinux_bootloader_cfg.stdout | length > 0
      ansible.builtin.command: grubby --update-kernel ALL --remove-args "selinux=0 enforcing=0"
      changed_when: true

# State set to enforcing because control 1.3.1.5 requires enforcing to be set
- name: "1.3.1.3 | PATCH | Ensure SELinux policy is configured"
  when: rhel8cis_rule_1_3_1_3
  tags:
    - level1-server
    - level1-workstation
    - automated
    - selinux
    - patch
    - NIST800-53R5_AC-3
    - NIST800-53R5_MP-2
    - rule_1.3.1.3
  ansible.posix.selinux:
    conf: /etc/selinux/config
    policy: "{{ rhel8cis_selinux_policy }}"
    state: "{{ rhel8cis_selinux_state }}"
  notify: Selinux relabel

# State set to enforcing because control 1.3.1.5 requires enforcing to be set
- name: "1.3.1.4 | PATCH | Ensure the SELinux mode is not disabled"
  when: rhel8cis_rule_1_3_1_4
  tags:
    - level1-server
    - level1-workstation
    - automated
    - selinux
    - patch
    - NIST800-53R5_SC-3
    - rule_1.3.1.4
  ansible.posix.selinux:
    conf: /etc/selinux/config
    policy: "{{ rhel8cis_selinux_policy }}"
    state: "{{ rhel8cis_selinux_state }}"
  notify: Selinux relabel

- name: "1.3.1.5 | PATCH | Ensure the SELinux state is enforcing"
  when: rhel8cis_rule_1_3_1_5
  tags:
    - level2-server
    - level2-workstation
    - automated
    - selinux
    - patch
    - NIST800-53R5_SC-3
    - NIST800-53R5_SI-6
    - rule_1.3.1.5
    - CCI-001084
    - CCI-002696
  ansible.posix.selinux:
    conf: /etc/selinux/config
    policy: "{{ rhel8cis_selinux_policy }}"
    state: enforcing
  notify: Selinux relabel

- name: "1.3.1.6 | AUDIT | Ensure no unconfined services exist"
  when: rhel8cis_rule_1_3_1_6
  tags:
    - level2-server
    - level2-workstation
    - automated
    - audit
    - services
    - NIST800-53R5_AC-3
    - NIST800-53R5_MP-2
    - rule_1.3.1.6
  vars:
    warn_control_id: '1.3.1.6'
  block:
    - name: "1.3.1.6 | AUDIT | Ensure no unconfined services exist | Find the unconfined services"
      ansible.builtin.shell: |
        set -o pipefail
        ps -eZ | grep unconfined_service_t | grep -Evw "tr|ps|egrep|bash|awk" | tr ':' ' ' | awk '{ print $NF }'
      args:
        executable: "{{ rhel8cis_shell_executable }}"
      register: discovered_unconf_services
      failed_when: false
      changed_when: false

    - name: "1.3.1.6 | WARNING | Ensure no unconfined services exist | Message on unconfined services"
      when:
        - discovered_unconf_services is defined
        - discovered_unconf_services.stdout | length > 0
      ansible.builtin.debug:
        msg: "Warning!! You have unconfined services: {{ discovered_unconf_services.stdout_lines }}"

    - name: "1.3.1.6 | WARNING | Ensure no unconfined services exist | warning count"
      when:
        - discovered_unconf_services is defined
        - discovered_unconf_services.stdout | length > 0
      ansible.builtin.import_tasks:
        file: warning_facts.yml

- name: "1.3.1.7 | PATCH | Ensure the MCS Translation Service (mcstrans) is not installed"
  when: rhel8cis_rule_1_3_1_7
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - NIST800-53R5_AC-3
    - NIST800-53R5_MP-2
    - rule_1.3.1.7
  ansible.builtin.package:
    name: mcstrans
    state: absent

- name: "1.3.1.8 | PATCH | Ensure SETroubleshoot is not installed"
  when: rhel8cis_rule_1_3_1_8
  tags:
    - level1-server
    - automated
    - selinux
    - patch
    - NIST800-53R5_AC-3
    - NIST800-53R5_MP-2
    - rule_1.3.1.8
  ansible.builtin.package:
    name: setroubleshoot
    state: absent
