---

- name: "1.1.7.1 | AUDIT | Ensure separate partition exists for /home"
  block:
      - name: "1.1.7.1 | AUDIT | Ensure separate partition exists for /home | Absent"
        debug:
            msg: "Warning!! {{ required_mount }} doesn't exist. This is a manual task"
        register: home_mount_absent
        changed_when: home_mount_absent.skipped is undefined
        when:
            - required_mount not in mount_names

      - name: "1.1.7.1 | AUDIT | Ensure separate partition exists for /home | Warn Count"
        set_fact:
            control_number: "{{ control_number }} + [ 'rule_1.1.7.1' ]"
            warn_count: "{{ warn_count | int + 1 }}"
        when:
            - required_mount not in mount_names

      - name: "1.1.7.1 | AUDIT | Ensure separate partition exists for /home | Present"
        debug:
            msg: "Congratulations: {{ required_mount }} exists."
        register: home_mount_present
        when:
            - required_mount in mount_names
  vars:
      required_mount: '/home'
  when:
      - rhel8cis_rule_1_1_7_1
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - mounts
      - rule_1.1.7.1
      - skip_ansible_lint

- name: |
    "1.1.7.2 | PATCH | Ensure nodev option set on /home partition
     1.1.7.3 | PATCH | Ensure nosuid option set on /home partition
     1.1.7.4 | PATCH | Ensure usrquota option set on /home partition
     1.1.7.5 | PATCH | Ensure grpquota option set on /home partition"
  mount:
      name: /home
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,{% if rhel8cis_rule_1_1_7_2 %}nodev,{% endif %}{% if rhel8cis_rule_1_1_7_3 %}nosuid,{% endif %}{% if rhel8cis_rule_1_1_7_4 %}usrquota,{% endif %}{% if rhel8cis_rule_1_1_7_5 %}grpquota{% endif %}
  with_items:
      - "{{ ansible_mounts }}"
  loop_control:
      label: "{{ item.device }}"
  notify: change_requires_reboot
  when:
      - home_mount_present is defined
      - item.mount == "/home"
      - rhel8cis_rule_1_1_7_1
      - rhel8cis_rule_1_1_7_2 or
        rhel8cis_rule_1_1_7_3 or
        rhel8cis_rule_1_1_7_4 or
        rhel8cis_rule_1_1_7_5
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - mounts
      - rule_1.1.7.2
      - rule_1.1.7.3
      - rule_1.1.7.4
      - skip_ansible_lint
