---
- name: "4.2.2.3 | PATCH | Ensure journald is configured to compress large log files"
  ansible.builtin.lineinfile:
      path: /etc/systemd/journald.conf
      regexp: 'Compress='
      line: Compress=yes
      insertafter: ^#Compress
      validate: /usr/bin/bash -n %s
  when:
      - rhel8cis_rule_4_2_2_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - journald
      - rule_4.2.2.3

- name: "4.2.2.4 | PATCH | Ensure journald is configured to write logfiles to persistent disk"
  ansible.builtin.lineinfile:
      path: /etc/systemd/journald.conf
      regexp: 'Storage='
      line: Storage=persistent
      state: present
      insertafter: ^#Storage
      validate: /usr/bin/bash -n %s
  when:
      - rhel8cis_rule_4_2_2_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - journald
      - rule_4.2.2.4
