---

- name: "4.1.2.1 | PATCH | Ensure at is restricted to authorized users"
  when:
      - rhel8cis_rule_4_1_2_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - cron
      - NIST800-53R5_AC-3
      - NIST800-53R5_MP-2
      - rule_4.1.2.1
  block:
      - name: "4.1.2.1 | PATCH | Ensure at is restricted to authorized users | Remove at.deny"
        ansible.builtin.file:
            path: /etc/at.deny
            state: absent

      - name: "4.1.2.1 | PATCH | Ensure at is restricted to authorized users  | Check if at.allow exists"
        ansible.builtin.stat:
            path: "/etc/at.allow"
        register: discovered_at_allow_state

      - name: "4.1.2.1 | PATCH | Ensure at is restricted to authorized users | Ensure at.allow is restricted to authorized users"
        ansible.builtin.file:
            path: /etc/at.allow
            state: '{{ "file" if discovered_at_allow_state.stat.exists else "touch" }}'
            owner: root
            group: root
            mode: '0600'
