---
# This is a playbook to test the tasks.
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  vars:
      ansible_user: "{{ lookup('env', 'USER') }}"
      system_is_container: true
      rhel8cis_selinux_disable: true
      role_name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      rhel8cis_firewall: none
      rhel8cis_rsyslog_ansiblemanaged: false
      # Crypto
      rhel8cis_rule_1_6_1: false
      # cron
      rhel8cis_rule_2_4_1_1: false
      # rsyslog enabled
      rhel8cis_rule_4_2_1_2: false
      # sudo password escalation
      rhel8cis_rule_5_2_4: false
      # logging enabled
      rhel8cis_rule_6_2_2_1: false

  pre_tasks:
  tasks:
      - name: "Include tasks"
        ansible.builtin.include_role:
            name: "{{ role_name }}"
